name: Deploy to AWS Lambda

on:
  workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Create Zip file for Lambda function
      run: cd src && zip -r lambda_function.zip .

    - name: AWS CLI v2 Deploy
      run: "aws lambda update-function-code \
          --function-name arn:aws:lambda:us-east-1:515966538249:function:getOrders \
          --zip-file fileb://src/lambda_function.zip"
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'us-east-1'